let g:coc_global_extensions = [
  \ 'coc-snippets',
  \ 'coc-actions',
  \ 'coc-sh',
  \ 'coc-lists',
  \ 'coc-tasks',
  \ 'coc-pairs',
  \ 'coc-floaterm',
  \ 'coc-fzf-preview',
  \ 'coc-emoji',
  \ 'coc-bookmark',
  \ 'coc-yaml',
  \ 'coc-python',
  \ 'coc-explorer',
  \ 'coc-svg',
  \ 'coc-vimlsp',
  \ 'coc-xml',
  \ 'coc-yank',
  \ 'coc-json',
  \ 'coc-marketplace',
  \ 'coc-tabnine',
  \ 'coc-highlight',
  \ ]

